export const points = {
  profileList: '/api/profileList',
  orgList: '/api/profileList?category=Organisation',
  upcomingEventlist:
    '/api/eventList?format=json&category=Careteams&sort=upcoming',
  previosEventlist: '/api/eventList?format=json&category=Careteams&sort=new',
  categoryList: '/api/categoryList',
  login: '/api/site?',
  messages: '/api/allConversations',
  messageDetail: '/api/getConversationHistory',
  albumList: '/api/albumList',
  uploadPhoto: '/api/photo',
  addActivity: '/api/status',
  activityList: '/api/statusList',
  issueList: '/api/issueList',
  registration: '/api/registration',
  eventList: '/api/eventList',
  memberList: '/api/memberList',
  profileManage: `/api/profileManagement?format=json`,
  profileInvitation: '/api/profileInvitation',
  documentList: '/api/documents',
  videoList: '/api/videoList',
  photoList: '/api/photoList',
  userFitnessRecord: '/api/userFitenessData',
  profileBackground: '/api/profileBackground',
  healthOverview: '/api/healthOverview',
  deleteDiagnosis: '/api/deleteDiagnosis',
  deleteProcedure: '/api/deleteProcedure',
  personalHealthDetails: '/api/personalHealthDetails',
  vaccine: '/api/vaccine',
  monitorReportHistory: '/api/sendMonitorReportHistory',
  familyHealthDetails: '/api/familyHealthDetails',
  sendReport: '/api/sendReport',
  progressNotes: '/api/progressNotes',
  manualDataEntry: '/api/manualDataEntry',
  eventDetail: '/api/event',
  eventImage: '/api/eventImage',
  deleteEventImage: '/api/deleteEventImage',
  profileRequestList: '/api/profileRequestList',
  profileRequest: '/api/profileRequest',
  addFriend: '/api/profileMembership',
  settings: '/api/settings',
  addDrug: '/api/bookmark',
  editDrug: '/api/deleteBookmark',
  addGroup: '/api/profile',
  messageReact: '/api/messageReact',
  postMessage:'/api/sendMessage'
};
