import { StyleSheet } from "react-native";
import { color, font, fontSize } from "../../theme";

export const styles = StyleSheet.create({
  callOutContainer: {
    alignItems: "center",
    justifyContent: "center",
    zIndex: 999999,
    width: "auto",
    position: "absolute",
    // left: 20,
    minHeight: 30,
  },
  contentWrapper: {
    marginRight: fontSize(10),
    width: "80%",
    // flex: 1,
  },
  modalTroubleView: {
    margin: fontSize(20),
    backgroundColor: color.white,
    borderRadius: fontSize(10),
    paddingRight: fontSize(100),
    paddingBottom: fontSize(20),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  centeredView: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: 'rgba(0, 0, 0, 0.8)',
  },
  callOutPinContainer: {
    maxHeight: fontSize(500),
    minHeight: fontSize(70),
    alignSelf: "center",
  },
  modelTxt: {
    fontSize: fontSize(14),
    fontFamily: font.Poppins_SemiBold,
    color: color.palette.black,
    marginBottom: fontSize(5),
  },
  modeldesc: {
    fontSize: fontSize(12.5),
    fontFamily: font.Poppins_Medium,
    color: color.palette.blackSecondary,
    // width:'90%',
    // marginLeft:fontSize(12.5),
  },
  container: { flex: 1 },
  map: { flex: 1 },
  markerContainer: {
    alignItems: "center",
    justifyContent: "center",
    // backgroundColor: 'pink',
  },
  marker: {
    width: 20,
    height: 20,
    backgroundColor: "red",
    borderRadius: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: 300,
    padding: 20,
    backgroundColor: "white",
    borderRadius: 10,
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  modalText: {
    fontSize: 14,
    marginBottom: 20,
  },
  closeButton: {
    padding: 10,
    backgroundColor: "red",
    borderRadius: 5,
  },
  closeText: {
    color: "white",
    fontWeight: "bold",
  },
  subWrapper: {
    backgroundColor: color.white,
    zIndex: 1000,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    flex: 1,
    alignSelf: "center",
    width: "100%",
  },
  bottomWrapper: {
    zIndex: 1000,
    marginTop: -2,
    elevation: 0,
    backgroundColor: "transparent",
    borderTopWidth: 16,
    borderRightWidth: 8,
    borderBottomWidth: 0,
    borderLeftWidth: 8,
    borderTopColor: "white",
    borderRightColor: "transparent",
    borderBottomColor: "transparent",
    borderLeftColor: "transparent",
  },
  labelText: {
    fontSize: fontSize(16),
    fontFamily: font.Poppins_SemiBold,
    color: color.palette.black,
    flex: 1,
    // marginBottom: fontSize(5),
  },
  labelTextWrapper: {
    width: "90%",
    // backgroundColor: 'grey',
  },
  addressLbl: {
    paddingTop: 5,
    fontSize: fontSize(14),
    fontFamily: font.Poppins_Regular,
    color: color.palette.black,
  },
  arrowIcon: {
    // padding: 5,
    flex: 1,
    // height: fontSize(35),
    // width: fontSize(35),
    // flex: 1,
    // alignSelf: 'flex-start',
    // marginLeft: fontSize(8),
  },
});
