name: Android Build

on:
  push:
    branches:
      - main
      - mobile_development

  pull_request:
    branches:
      - main
      - mobile_development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: yarn

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create ENV File
        run: |
          echo "${{ secrets.ENV_FILES }}" > .env

      - name: Verify ENV File Exists
        run: |
          if [ -f .env ]; then
            echo ".env file created successfully"
          else
            echo ".env file missing"
            exit 1
          fi

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE }}" | base64 --decode > android/app/epione-release.keystore

      - name: Grant Execute Permission
        run: chmod +x android/gradlew

      - name: Build Android Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk