name: iOS Build

on:
  push:
    branches:
      - main
      - mobile_development

  pull_request:
    branches:
      - main
      - mobile_development

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0
          cache: yarn

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

       - name: Install Pods
        run: |
          cd ios
          pod install --repo-update

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData

      - name: Build iOS
        run: |
          cd ios
          xcodebuild \
            -workspace EpioneCares.xcworkspace \
            -scheme EpioneCares \
            -sdk iphonesimulator \
            -configuration Release \
            -derivedDataPath build \
            build

      - name: Upload iOS Build Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-build-data
          path: ios/build